/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_socks_settings (void)
{
  GtkWidget *window_socks_settings;
  GtkWidget *vbox1;
  GtkWidget *vbox2;
  GtkWidget *frame3;
  GtkWidget *table1;
  GtkWidget *radiobutton_v4;
  GSList *radiobutton_v4_group = NULL;
  GtkWidget *radiobutton_v5;
  GtkWidget *entry_socks_addr;
  GtkWidget *entry_socks_port;
  GtkWidget *label5;
  GtkWidget *label4;
  GtkWidget *label3;
  GtkWidget *frame_pwd_auth;
  GtkWidget *table_pwd_auth;
  GtkWidget *entry_socks_user;
  GtkWidget *entry_socks_password;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *checkbutton_pwd_auth;
  GtkWidget *hseparator1;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window_socks_settings = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (window_socks_settings), 8);
  gtk_window_set_title (GTK_WINDOW (window_socks_settings), "Socks protocol settings");
  gtk_window_set_position (GTK_WINDOW (window_socks_settings), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (window_socks_settings), TRUE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window_socks_settings), vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox2), frame3, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 8);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame3), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 8);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 8);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 10);

  radiobutton_v4 = gtk_radio_button_new_with_mnemonic (NULL, "version 4");
  gtk_widget_show (radiobutton_v4);
  gtk_table_attach (GTK_TABLE (table1), radiobutton_v4, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, radiobutton_v4, "Socks version 4 protocol, authentication not supported.", NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_v4), radiobutton_v4_group);
  radiobutton_v4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_v4));

  radiobutton_v5 = gtk_radio_button_new_with_mnemonic (NULL, "version 5");
  gtk_widget_show (radiobutton_v5);
  gtk_table_attach (GTK_TABLE (table1), radiobutton_v5, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, radiobutton_v5, "Socks version 5 protocol, supports user/password authentication (preferred)", NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_v5), radiobutton_v4_group);
  radiobutton_v4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_v5));

  entry_socks_addr = gtk_entry_new ();
  gtk_widget_show (entry_socks_addr);
  gtk_table_attach (GTK_TABLE (table1), entry_socks_addr, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, entry_socks_addr, "Name or IP in dot notation of the socks server", NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry_socks_addr), 63);

  entry_socks_port = gtk_entry_new ();
  gtk_widget_show (entry_socks_port);
  gtk_table_attach (GTK_TABLE (table1), entry_socks_port, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, entry_socks_port, "Port number where the socks server is located", NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry_socks_port), 5);

  label5 = gtk_label_new ("Server Port (1/65535)");
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label5), 1, 0.5);

  label4 = gtk_label_new ("Server address");
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label4), 1, 0.5);

  label3 = gtk_label_new ("<b>Server settings</b>");
  gtk_widget_show (label3);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label3);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  frame_pwd_auth = gtk_frame_new (NULL);
  gtk_widget_show (frame_pwd_auth);
  gtk_box_pack_start (GTK_BOX (vbox2), frame_pwd_auth, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_pwd_auth), 8);

  table_pwd_auth = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table_pwd_auth);
  gtk_container_add (GTK_CONTAINER (frame_pwd_auth), table_pwd_auth);
  gtk_table_set_row_spacings (GTK_TABLE (table_pwd_auth), 8);
  gtk_table_set_col_spacings (GTK_TABLE (table_pwd_auth), 8);

  entry_socks_user = gtk_entry_new ();
  gtk_widget_show (entry_socks_user);
  gtk_table_attach (GTK_TABLE (table_pwd_auth), entry_socks_user, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, entry_socks_user, "Username to pass to the socks5 server", NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry_socks_user), 31);

  entry_socks_password = gtk_entry_new ();
  gtk_widget_show (entry_socks_password);
  gtk_table_attach (GTK_TABLE (table_pwd_auth), entry_socks_password, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, entry_socks_password, "Password for the socks5 server", NULL);
  gtk_entry_set_max_length (GTK_ENTRY (entry_socks_password), 31);
  gtk_entry_set_visibility (GTK_ENTRY (entry_socks_password), FALSE);

  label6 = gtk_label_new ("Username");
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table_pwd_auth), label6, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label6), 1, 0.5);

  label7 = gtk_label_new ("Password");
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table_pwd_auth), label7, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label7), 1, 0.5);

  checkbutton_pwd_auth = gtk_check_button_new_with_mnemonic ("Password authentication");
  gtk_widget_show (checkbutton_pwd_auth);
  gtk_frame_set_label_widget (GTK_FRAME (frame_pwd_auth), checkbutton_pwd_auth);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, FALSE, FALSE, 4);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);

  button1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button1, "Confirm socks settings...", NULL);

  button2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, button2, "Discard changes of this form...", NULL);

  g_signal_connect ((gpointer) window_socks_settings, "delete_event",
                    G_CALLBACK (on_socks_ko_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_v4, "clicked",
                    G_CALLBACK (on_radiobutton_v4_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_v5, "clicked",
                    G_CALLBACK (on_radiobutton_v5_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_pwd_auth, "toggled",
                    G_CALLBACK (on_checkbutton_pwd_auth_toggled),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_socks_ok_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_socks_ko_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_socks_settings, window_socks_settings, "window_socks_settings");
  GLADE_HOOKUP_OBJECT (window_socks_settings, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window_socks_settings, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (window_socks_settings, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (window_socks_settings, table1, "table1");
  GLADE_HOOKUP_OBJECT (window_socks_settings, radiobutton_v4, "radiobutton_v4");
  GLADE_HOOKUP_OBJECT (window_socks_settings, radiobutton_v5, "radiobutton_v5");
  GLADE_HOOKUP_OBJECT (window_socks_settings, entry_socks_addr, "entry_socks_addr");
  GLADE_HOOKUP_OBJECT (window_socks_settings, entry_socks_port, "entry_socks_port");
  GLADE_HOOKUP_OBJECT (window_socks_settings, label5, "label5");
  GLADE_HOOKUP_OBJECT (window_socks_settings, label4, "label4");
  GLADE_HOOKUP_OBJECT (window_socks_settings, label3, "label3");
  GLADE_HOOKUP_OBJECT (window_socks_settings, frame_pwd_auth, "frame_pwd_auth");
  GLADE_HOOKUP_OBJECT (window_socks_settings, table_pwd_auth, "table_pwd_auth");
  GLADE_HOOKUP_OBJECT (window_socks_settings, entry_socks_user, "entry_socks_user");
  GLADE_HOOKUP_OBJECT (window_socks_settings, entry_socks_password, "entry_socks_password");
  GLADE_HOOKUP_OBJECT (window_socks_settings, label6, "label6");
  GLADE_HOOKUP_OBJECT (window_socks_settings, label7, "label7");
  GLADE_HOOKUP_OBJECT (window_socks_settings, checkbutton_pwd_auth, "checkbutton_pwd_auth");
  GLADE_HOOKUP_OBJECT (window_socks_settings, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window_socks_settings, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window_socks_settings, button1, "button1");
  GLADE_HOOKUP_OBJECT (window_socks_settings, button2, "button2");
  GLADE_HOOKUP_OBJECT_NO_REF (window_socks_settings, tooltips, "tooltips");

  return window_socks_settings;
}

