/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_socks_settings (void);
GtkWidget* create_window_preferences (void);
GtkWidget* create_window_wizard (void);
GtkWidget* create_window_mccp_status (void);
GtkWidget* create_window_macro_editor (void);
GtkWidget* create_window_main (void);
GtkWidget* create_window_connect (void);
GtkWidget* create_window_triggers (void);
GtkWidget* create_window_classes (void);
GtkWidget* create_window_aliases (void);
GtkWidget* create_window_gags (void);
GtkWidget* create_window_complete (void);
GtkWidget* create_window_about (void);
GtkWidget* create_window_buttons (void);
