/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_socks_settings (void);
GtkWidget* create_window_preferences (void);
GtkWidget* create_window_wizard (void);
GtkWidget* create_window_mccp_status (void);
